2025-06-04 11:52:42,325 INFO    MainThread:20692 [wandb_init.py:setup_run_log_directory():724] Logging user logs to C:\Users\Erick\Desktop\Project\Jupyter\DlhJupyterNotebook\wandb\run-20250604_115242-xtuts2vl\logs\debug.log
2025-06-04 11:52:42,325 INFO    MainThread:20692 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to C:\Users\Erick\Desktop\Project\Jupyter\DlhJupyterNotebook\wandb\run-20250604_115242-xtuts2vl\logs\debug-internal.log
2025-06-04 11:52:42,325 INFO    MainThread:20692 [wandb_init.py:init():852] calling init triggers
2025-06-04 11:52:42,325 INFO    MainThread:20692 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-06-04 11:52:44,204 INFO    MainThread:20692 [wandb_init.py:init():893] starting backend
2025-06-04 11:52:44,204 INFO    MainThread:20692 [wandb_init.py:init():897] sending inform_init request
2025-06-04 11:52:44,210 INFO    MainThread:20692 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-06-04 11:52:44,211 INFO    MainThread:20692 [wandb_init.py:init():907] backend started and connected
2025-06-04 11:52:44,214 INFO    MainThread:20692 [wandb_init.py:init():1005] updated telemetry
2025-06-04 11:52:44,262 INFO    MainThread:20692 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-06-04 11:52:44,958 INFO    MainThread:20692 [wandb_init.py:init():1104] starting run threads in backend
2025-06-04 11:52:45,114 INFO    MainThread:20692 [wandb_run.py:_console_start():2573] atexit reg
2025-06-04 11:52:45,115 INFO    MainThread:20692 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-06-04 11:52:45,115 INFO    MainThread:20692 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-06-04 11:52:45,115 INFO    MainThread:20692 [wandb_run.py:_redirect():2513] Redirects installed.
2025-06-04 11:52:45,115 INFO    MainThread:20692 [wandb_init.py:init():1150] run started, returning control to user process
2025-06-04 11:52:49,437 INFO    MsgRouterThr:20692 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 3 handles.
